config/routes.rb
Project1::Application.routes.draw do
  resources :appointments

  get "events/index"
  get "appoinments/" => "appoinemnts#index" 
  get "pages/calendar"
  get "pages/home"
  get "pages/project_2"
  get "calendar/" => "pages#calendar"
   root 'pages#home'

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:time, :description, :month, :day, :year)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def new
    @post = Event.new
  end
  
  def index
    @posts = Event.all
  end
  
  def create
    @post = Event.new(post_params)
  end
  
  def remove
    @post = Event.destoy
  end
  
  private
  def post_params
    params.require(events).permit(:time, :description, :date)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Description</th>
      <th>Month</th>
      <th>Day</th>
      <th>Year</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.time %></td>
        <td><%= appointment.description %></td>
        <td><%= appointment.month %></td>
        <td><%= appointment.day %></td>
        <td><%= appointment.year %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appointment.description %>
</p>

<p>
  <strong>Month:</strong>
  <%= @appointment.month %>
</p>

<p>
  <strong>Day:</strong>
  <%= @appointment.day %>
</p>

<p>
  <strong>Year:</strong>
  <%= @appointment.year %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/events/index.html.erb
<h1>Events</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/calendar.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <script src="application.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixedtop" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <h4 class="navbar-brand" id="brand"><font color="white">Jonathan Lei</font></h4>
        </div>
      </div>
    </nav>
   
    <p>Time</p>
    <select id="time">
      <option></option>
      <option>1:00</option>
      <option>2:00</option>
      <option>3:00</option>
      <option>4:00</option>
      <option>5:00</option>
      <option>6:00</option>
      <option>7:00</option>
      <option>8:00</option>
      <option>9:00</option>
      <option>10:00</option>
      <option>11:00</option>
      <option>13:00</option>
      <option>14:00</option>
      <option>15:00</option>
      <option>16:00</option>
      <option>17:00</option>
      <option>18:00</option>
      <option>19:00</option>
      <option>20:00</option>
      <option>21:00</option>
      <option>22:00</option>
      <option>23:00</option>
      <option>24:00</option>
    </select>
    <p>Description</p>
    <input type="text" id="description"></input><br></br>
    
    <table id="calendar" border="1" width="99%">
      <thead>
	      <tr>
	        <th><a id = yearBack> << </a></th>
	        <th><a id=monthBack> < </a></th>
	        <th id=monthYear colspan="3"></th>
	        <th><a id=monthForward> > </a></th>
	        <th><a id=yearForward> >> </a></th>
	      </tr>
	      
	      <tr>
	        <th>Sun</th>
	        <th>Mon</th>
	        <th>Tues</th>
	        <th>Wed</th>
	        <th>Thur</th>
	        <th>Fri</th>
	        <th>Sat</th>
	      
	      </tr>
      </thead>
      <tbody id="tablebody">
	      <tr class="week"></tr>
	      <tr class="week"></tr>
	      <tr class="week"></tr>
	      <tr class="week"></tr>
	      <tr class="week"></tr>
	      <tr class="week"></tr>
      </tbody>
      
    </table>
    
    
  </body>
</html>

app/views/pages/home.html.erb
<h1>Jonathan Lei</h1>

<table>
   <thead>
       <tr>
           <th>Project Name</th>
           <th>Description</th>
           <th>URL</th>
       </tr>
   </thead>
   <tbody>
       <% PROJECTS.each do |project, data| %>
           <tr>
               <td><%= project %></td>
               <td><%= data['description'] %></td>
               <td><%= link_to data['url'], data['url'] %></td>
           </tr>
       <% end %>
   </tbody>
</table>

app/views/pages/project_2.html.erb
<h1>Project 2 summary</h1>
<p>
  For this project I installed the Twitter Bootstrap gem on terminal.
  I then created a new page in the views for project 2.  Added the routes for the new
  page in the routes.rb.  After adding the routes, I went to the stylesheets and added
  a bootstrap_and_overides.css.scss file where I imported bootstrap.  In the javascripts
  folder I modified the application.js to require bootstrap.  Finally I went back to the
  page I created for this section and wrote my summary.
</p>